language: ruby
rvm:
  - 2.0.0

script:
  - RAILS_ENV=test bundle exec rake db:create --trace
  - bundle exec rspec spec

addons:
  code_climate:
    repo_token: e41fcb8217e7a166de225186d9b906b7a1cdae790e046b3fafe7aad198e045c6
