require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DeliveryServicesController do

  # This should return the minimal set of attributes required to create a valid
  # DeliveryService. As you add validations to DeliveryService, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DeliveryServicesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all delivery_services as @delivery_services" do
      delivery_service = DeliveryService.create! valid_attributes
      get :index, {}, valid_session
      assigns(:delivery_services).should eq([delivery_service])
    end
  end

  describe "GET show" do
    it "assigns the requested delivery_service as @delivery_service" do
      delivery_service = DeliveryService.create! valid_attributes
      get :show, {:id => delivery_service.to_param}, valid_session
      assigns(:delivery_service).should eq(delivery_service)
    end
  end

  describe "GET new" do
    it "assigns a new delivery_service as @delivery_service" do
      get :new, {}, valid_session
      assigns(:delivery_service).should be_a_new(DeliveryService)
    end
  end

  describe "GET edit" do
    it "assigns the requested delivery_service as @delivery_service" do
      delivery_service = DeliveryService.create! valid_attributes
      get :edit, {:id => delivery_service.to_param}, valid_session
      assigns(:delivery_service).should eq(delivery_service)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DeliveryService" do
        expect {
          post :create, {:delivery_service => valid_attributes}, valid_session
        }.to change(DeliveryService, :count).by(1)
      end

      it "assigns a newly created delivery_service as @delivery_service" do
        post :create, {:delivery_service => valid_attributes}, valid_session
        assigns(:delivery_service).should be_a(DeliveryService)
        assigns(:delivery_service).should be_persisted
      end

      it "redirects to the created delivery_service" do
        post :create, {:delivery_service => valid_attributes}, valid_session
        response.should redirect_to(DeliveryService.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved delivery_service as @delivery_service" do
        # Trigger the behavior that occurs when invalid params are submitted
        DeliveryService.any_instance.stub(:save).and_return(false)
        post :create, {:delivery_service => { "name" => "invalid value" }}, valid_session
        assigns(:delivery_service).should be_a_new(DeliveryService)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DeliveryService.any_instance.stub(:save).and_return(false)
        post :create, {:delivery_service => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested delivery_service" do
        delivery_service = DeliveryService.create! valid_attributes
        # Assuming there are no other delivery_services in the database, this
        # specifies that the DeliveryService created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DeliveryService.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => delivery_service.to_param, :delivery_service => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested delivery_service as @delivery_service" do
        delivery_service = DeliveryService.create! valid_attributes
        put :update, {:id => delivery_service.to_param, :delivery_service => valid_attributes}, valid_session
        assigns(:delivery_service).should eq(delivery_service)
      end

      it "redirects to the delivery_service" do
        delivery_service = DeliveryService.create! valid_attributes
        put :update, {:id => delivery_service.to_param, :delivery_service => valid_attributes}, valid_session
        response.should redirect_to(delivery_service)
      end
    end

    describe "with invalid params" do
      it "assigns the delivery_service as @delivery_service" do
        delivery_service = DeliveryService.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DeliveryService.any_instance.stub(:save).and_return(false)
        put :update, {:id => delivery_service.to_param, :delivery_service => { "name" => "invalid value" }}, valid_session
        assigns(:delivery_service).should eq(delivery_service)
      end

      it "re-renders the 'edit' template" do
        delivery_service = DeliveryService.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DeliveryService.any_instance.stub(:save).and_return(false)
        put :update, {:id => delivery_service.to_param, :delivery_service => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested delivery_service" do
      delivery_service = DeliveryService.create! valid_attributes
      expect {
        delete :destroy, {:id => delivery_service.to_param}, valid_session
      }.to change(DeliveryService, :count).by(-1)
    end

    it "redirects to the delivery_services list" do
      delivery_service = DeliveryService.create! valid_attributes
      delete :destroy, {:id => delivery_service.to_param}, valid_session
      response.should redirect_to(delivery_services_url)
    end
  end

end
